- name: router tasks
  hosts: openwrt
  gather_facts: false
  roles:
    - community.openwrt.init
  tasks:
    - name: Gather facts
      community.openwrt.setup:

    - name: include router tasks
      include_tasks: "{{ item }}"
      tags: always # https://serverfault.com/a/1048724
      loop: "{{ lookup('fileglob', 'tasks/router/*.yaml', wantlist=True) }}"
