- tags: amnezia
  block:
    - name: get arch
      community.openwrt.command:
        uses_shell: true
        cmd: source /etc/openwrt_release; echo "${DISTRIB_ARCH}"
      register: DISTRIB_ARCH
      changed_when: false
    - name: install amnezia packages
      # looks like opkg fails to check if package is installed if URL is used
      # so I use shell instead
      community.openwrt.command:
        uses_shell: true
        cmd: >-
          opkg list-installed {{package}}
          | grep {{package}}
          || opkg install https://github.com/Slava-Shchipunov/awg-openwrt/releases/download/v{{ansible_distribution_version}}/{{package}}_v{{ansible_distribution_version}}_{{DISTRIB_ARCH.stdout}}_{{openwrt_board.release.target|replace('/','_')}}.ipk
      loop:
        - amneziawg-tools
        - kmod-amneziawg
        - luci-proto-amneziawg
      loop_control:
        loop_var: package
    #- name: restart network
    #  shell: "service network restart"
    - name: vpn_domains
      community.openwrt.uci:
        command: section
        config: dhcp
        type: ipset
        find:
          device: radio0
          ssid: My SSID
        value:
          encryption: none
        replace: yes
